apiVersion: v1
kind: Pod
metadata: 
  name: empty-dirctory

spec: 
  containers:
  - name: nginx
    image: nginx
    ports:
    -  containerPort: 80
    volumeMounts:
    - name: empty-directory-volume
      mountPath: /data
  volumes:
  - name: empty-directory-volume
    emptyDir: {}
