apiVersion: v1
kind: Pod
metadata:
  name: hostpath-demo
  namespace: default

spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: host-storage
          mountPath: /data    #path inside the pod

  volumes:
    - name: host-storage
      hostPath:
        path: /home/ubuntu/data    #path inside the vm/node
        type: DirectoryOrCreate
