apiVersion: v1
kind: Pod
metadata:
  name: nginx-ebs
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: ebs-volume
          mountPath: /data

  volumes:
    - name: ebs-volume
      persistentVolumeClaim:
        claimName: dynamic-pvc
