apiVersion: v1
kind: Pod
metadata:
  name: nginx-pvc

spec:
  containers:
    - name: nginx
      image: nginx

      volumeMounts:
        - name: app-storage
          mountPath: /data

  volumes:
    - name: app-storage
      persistentVolumeClaim:
        claimName: my-pvc
